#!/usr/bin/env bash
# Copyright 2026 marshone
# Licensed under the Apache License, Version 2.0

set -euo pipefail

SCRIPT_NAME=$(basename "$0")
VERSION="0.1.3"

# Allow custom prefix, defaulting to "struct_alignment"
ALIGNMENT_PREFIX="${ALIGNMENT_PREFIX:-struct_alignment}"

show_help() {
    echo "Usage: $0 [options/commands] <target-package-directory>"
    echo ""
    echo "Commands:"
    echo "  clean          Remove all generated alignment test files recursively from current dir"
    echo "  ls             List all package directories containing generated alignment tests"
    echo ""
    echo "Options:"
    echo "  -h, --help     Show this help message and exit"
    echo "  -v, --version  Show version information and exit"
    echo ""
    echo "Example:"
    echo "  $0 ./internal/control"
    echo "  ALIGNMENT_PREFIX=zz_generated_alignment $0 ./internal/control"
}

# Handle standard commands and options
if [ "$#" -eq 1 ]; then
    case "$1" in
        -h|--help|help)
            show_help
            exit 0
            ;;
        -v|--version|version)
            echo "$SCRIPT_NAME version $VERSION"
            exit 0
            ;;
        clean)
            echo "Cleaning up generated alignment tests (*${ALIGNMENT_PREFIX}_test.go)..."

            # Trouve uniquement les fichiers avec le bon préfixe ET la signature de génération
            mapfile -t GEN_FILES < <(find . -type f -name "*${ALIGNMENT_PREFIX}_test.go" -exec grep -l "Auto Generated by github.com/marshone/aligncheck" {} + 2>/dev/null)

            if [ ${#GEN_FILES[@]} -eq 0 ]; then
                echo "No generated alignment files found to clean."
                exit 0
            fi

            DELETED_COUNT=0
            for file in "${GEN_FILES[@]}"; do
                rm -i "$file"

                if [ ! -f "$file" ]; then
                    echo "  Deleted: $file"
                    ((DELETED_COUNT++))
                else
                    echo "  Skipping: $file"
                fi
            done

            echo "Successfully cleaned $DELETED_COUNT generated file(s)."
            exit 0
            ;;
        ls)
            echo "Searching for generated alignment tests..."

            # Utilise find + grep de manière performante pour lister uniquement les fichiers contenant la signature
            mapfile -t GEN_FILES < <(find . -type f -name "*_test.go" -exec grep -l "Auto Generated by github.com/marshone/aligncheck" {} + 2>/dev/null)

            if [ ${#GEN_FILES[@]} -eq 0 ]; then
                echo "No generated alignment files found."
                exit 0
            fi

            for file in "${GEN_FILES[@]}"; do
                echo "  Found: $file"
            done
            exit 0
            ;;
    esac
fi

# We strictly expect exactly one argument for directory targeting if not running commands
if [ "$#" -ne 1 ]; then
    show_help
    exit 1
fi

TARGET_DIR="${1}"

# Clean trailing slashes
TARGET_DIR="${TARGET_DIR%"${TARGET_DIR##*[!/]}"}"

if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: Directory '$TARGET_DIR' does not exist."
    echo "For help, run: $0 --help"
    exit 1
fi

OUT_FILE="${TARGET_DIR}/${ALIGNMENT_PREFIX}_test.go"

if [ -f "$OUT_FILE" ]; then
    echo -n "Warning: '$OUT_FILE' already exists. Overwrite? (y/N): "
    read -r response
    if [[ ! "$response" =~ ^[yY](es)?$ ]]; then
        echo "Aborting generation. No changes made."
        exit 0
    fi
fi

PKG_NAME=$(grep -r "package " "$TARGET_DIR" --include="*.go" --exclude="*_test.go" -h | head -n 1 | awk '{print $2}')

if [ -z "$PKG_NAME" ]; then
    echo "Error: Could not determine package name in '$TARGET_DIR'."
    exit 1
fi

mapfile -t STRUCTS < <(grep -r "type " "$TARGET_DIR" --include="*.go" --exclude="*_test.go" -h \
    | grep -E "type[[:space:]]+[A-Za-z0-9_]+[[:space:]]+struct" \
    | sed -E 's/.*type[[:space:]]+([A-Za-z0-9_]+)[[:space:]]+struct.*/\1/' \
    | sort -u)

if [ ${#STRUCTS[@]} -eq 0 ]; then
    echo "No structs found in '$TARGET_DIR'."
    exit 0
fi

GEN_DATE=$(date +"%Y-%m-%d %H:%M:%S")

echo "Generating alignment test for package '$PKG_NAME' with ${#STRUCTS[@]} structs..."

{
    echo "// Auto Generated by github.com/marshone/aligncheck"
    echo "// Using $SCRIPT_NAME $TARGET_DIR"
    echo "// $SCRIPT_NAME - $VERSION on $GEN_DATE"
    echo "// DO NOT EDIT (except if you know what your are doing)"
    echo ""
    echo "package $PKG_NAME"
    echo ""
    echo "import ("
    echo "	\"testing\""
    echo ""
    echo "	\"github.com/marshone/aligncheck\""
    echo ")"
    echo ""
    echo "func TestStructAlignments(t *testing.T) {"
    echo "	registry := map[string]interface{}{"
    for struct in "${STRUCTS[@]}"; do
        echo "		\"$struct\": $struct{},"
    done
    echo "	}"
    echo ""
    echo "	aligncheck.AssertAllInPackageAligned(t, registry)"
    echo "}"
} > "$OUT_FILE"

if command -v gofmt >/dev/null 2>&1; then
    gofmt -w "$OUT_FILE"
fi

echo "Successfully wrote $OUT_FILE! Run 'go test -v ${TARGET_DIR}/...' to verify."
